(Parent Chandler John)
(Parent Chandler Pam)
(Parent Chandler Adam)
(Parent Chandler Jane)

(Parent Monica Adam)
(Parent Monica Jane)
(Parent Monica Pam)
(Parent Monica John)


(Parent John Bob)

(Parent Pam Tim)
(Parent Pam Kim)

(Parent Adam Eve)

(Parent Jane Joey)

(Female Monica)
(Female Pam)
(Female Jane)
(Female Kim)
(Female Eve)

(Male Chandler)
(Male John)
(Male Adam)
(Male Bob)
(Male Tim)
(Male Joey)